apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |

    #persistence true
    #persistence_location /var/lib/mosquitto/

    #log_dest file /var/log/mosquitto/mosquitto.log
    
    # Listener for outside connections
    listener 1883
    allow_anonymous true

    listener 9001
    protocol websockets
    allow_anonymous true
