apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttx
  template:
    metadata:
      labels:
        app: mqttx
    spec:
      containers:
      - name: mqttx
        image: emqx/mqttx-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: mqttx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
  selector:
    app: mqttx

