[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  urls = ["http://influxdb-service:32400"] # Adjust this to point to your InfluxDB instance
  database = "telegraf"
  skip_database_creation = true

# MQTT Consumer Input Configuration
[[inputs.mqtt_consumer]]
  servers = ["tcp://nanomq-service:32200"] # Adjust this to your MQTT broker address
  qos = 0
  connection_timeout = "30s"
  topics = [
    "bus_metrics/+/+"
  ]
  persistent_session = false
  client_id = "telegraf-host01"

  # Data format to consume.
  # Each data format has its own unique set of configuration options, read
  # more about them here:
  # https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json"

